another try at an auto-deployment script
git-svn-id: http://svn.pdxruby.org/repos/www/trunk@83 f0fbaf97-c700-0410-a5eb-8ea856f8537e

diff --git a/script/deploy b/script/deploy
--- a/script/deploy
+++ b/script/deploy
@@ -1,37 +1,66 @@
-#!/usr/bin/env ruby
+#!/bin/sh -x
 
+errors_email=johnl
+repo_url=http://svn.pdxruby.org/repos/www/trunk
+dev=~/sites/dev
+current_tree=$dev/current
+custom_tree=$dev/custom
 
-echo 'broken!'
-exit 1
+######################################################################
 
-#base=~/sites/dev
-base=/tmp/dev
-
-repos=$1; shift
-rev=$1; shift
-
-if [ ! "$repos" -o ! "$rev"]; then
-  echo "Usage:"
-  exit 1
+if [ $# != 2 ]; then
+    echo "Usage: $0 repository path revision"
+    exit 1
 fi
 
-dev_rev=r$rev
+repo=$1; shift
+rev=$1; shift
 
-svn co http://svn.pdxruby.org/repos/www/trunk $dev_rev
+######################################################################
 
-cd $dev_rev
+function check_out {
+    echo 'WOULD:' svn co -r$2 $1 $3
+    cp -rp ~/src/projects/pdxruby.org/trunk $3
+}
 
-mkdir -p $dev_rev/log
+function config_tree {
+    for file in `cd $custom_tree && find . -type f `; do
+        cp $custom_tree/$file $new_tree/$file
+    done
+}
 
-{ rake 2>&1 >log/build.log || mail -s "Tests failed for revision $rev" $mail <log/build.log; exit 1 }
+function initialize_logs {
+    mkdir -p $new_tree/log
+    for name in development test production; do
+        log=$new_tree/log/$name
+        touch $log
+        chmod 0666 $log
+    done
+}
 
-{ cd custom && find . -type f -exec cp '{}' '$dev_rev/{}' \; }
+function run_tests {
+    rake 2>&1 >$new_tree/log/build.log
+    echo '[not exiting]'
+}
 
-for log in development test production; do
-  touch $log
-  chmod 0666 $dev_rev/log/$log
-end
+######################################################################
 
-cd $base
+new_tree=$dev/r$rev
 
-relink current $dev_rev
+check_out $repo_url $rev $new_tree
+
+if ! config_tree; then
+    echo "failed to configure tree"
+    exit 1
+fi
+
+initialize_logs
+
+if ! run_tests; then
+    mail -s "Revision $rev failed tests" $errors_email < $new_tree/log/build.log
+    exit 1
+fi
+
+ln -sf $new_tree $current_tree
+
+######################################################################
